### ISSUE TITLE
state of this extension

### ISSUE THREAD

**Issue by streamnsight** [maxdemarzi/graph_processing#4]
This code does not seem to have changed in a while. 
Does that means it's best in class, or abandoned?

If not maintained, what is the main reason? Lack of time? Better solutions out there?

I'm looking at neo4j, and will need similar algorithms; 
Just trying to find the best solution for real time computations on graphs and subgraphs. 
Is this even a viable option?

Thanks for the feedback.

**Comment by maxdemarzi** [comment]
This code has been moved over to APOC. See:
https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_graph_algorithms
